"""add timestamps fields

Revision ID: 5b8e45e43aea
Revises: c582c37d3309
Create Date: 2025-10-19 18:50:09.303663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8e45e43aea'
down_revision: Union[str, Sequence[str], None] = 'c582c37d3309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ai_models', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ai_models', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_ai_models_deleted_at'), 'ai_models', ['deleted_at'], unique=False)
    op.add_column('ai_providers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ai_providers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ai_providers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_ai_providers_deleted_at'), 'ai_providers', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_providers_deleted_at'), table_name='ai_providers')
    op.drop_column('ai_providers', 'deleted_at')
    op.drop_column('ai_providers', 'updated_at')
    op.drop_column('ai_providers', 'created_at')
    op.drop_index(op.f('ix_ai_models_deleted_at'), table_name='ai_models')
    op.drop_column('ai_models', 'deleted_at')
    op.drop_column('ai_models', 'updated_at')
    op.drop_column('ai_models', 'created_at')
    # ### end Alembic commands ###
